// Supabase requests test: what the data layer (js/store.js) actually sends to the database when a
// post is created, updated and deleted. Supabase is faked, so the real database is never used.
// Run: npm test
import { chromium } from 'playwright';
import { serve } from '../scripts/serve.mjs';

const server = await serve(0);
const base = `http://localhost:${server.address().port}/`;
const browser = await chromium.launch();
const context = await browser.newContext({ serviceWorkers: 'block' });
await context.route('**/js/config.js', (r) => r.fulfill({ contentType: 'text/javascript',
  body: "window.LL_CONFIG = { supabaseUrl: 'https://fake-project.supabase.co', supabaseAnonKey: 'sb_publishable_test' };" }));
let failures = 0;
function check(ok, label) {
  console.log(`${ok ? 'ok  ' : 'FAIL'} ${label}`);
  if (!ok) failures++;
}

const existing = { id: 7, type: 'verse', status: 'published', publish_at: '2026-01-01T00:00:00Z', title: 'Psalm 4:8', slug: 'psalm-4-8',
  show_on_today: true, media_url: null, fields: { verse: 'In peace', ref: 'Psalm 4:8' }, author_email: 'a@example.org', created_at: '2026-01-01T00:00:00Z' };
const calls = [];
await context.route('https://fake-project.supabase.co/**', (r) => {
  const req = r.request(), url = new URL(req.url());
  if (req.method() === 'GET') return r.fulfill({ contentType: 'application/json', body: JSON.stringify([existing]) });
  const body = req.postData() ? JSON.parse(req.postData()) : null;
  calls.push({ method: req.method(), query: url.search, body });
  // Like the real table: `id` is generated by the database and can't be written.
  if (body && 'id' in body) {
    return r.fulfill({ status: 400, contentType: 'application/json', body: JSON.stringify({ code: '428C9', message: 'column "id" can only be updated to DEFAULT' }) });
  }
  return r.fulfill({ status: req.method() === 'POST' ? 201 : 200, contentType: 'application/json', body: JSON.stringify({ ...existing, ...body, id: 7 }) });
});

const page = await context.newPage();
await page.goto(base + 'studio/');
await page.waitForFunction(() => window.LLStore && window.LLStore.mode === 'supabase');
const save = (post) => page.evaluate((p) => window.LLStore.savePost(p, 'me@example.org').then((rec) => ({ ok: true, rec }), (e) => ({ ok: false, error: e.message })), post);

const updated = await save({ ...existing, title: 'Psalm 4:8', fields: { verse: 'In peace I will both lay myself down and sleep.', ref: 'Psalm 4:8' } });
const patch = calls.find((c) => c.method === 'PATCH');
check(updated.ok, `update: editing an existing post is accepted ${updated.error || ''}`);
check(!!patch && !('id' in patch.body), 'update: the post id is not written');
check(!!patch && patch.query.includes('id=eq.7'), 'update: the change is aimed at the right post');
check(!!patch && patch.body.slug === 'psalm-4-8', 'update: the post keeps its address (slug)');

const { id, slug, created_at, author_email, ...fresh } = existing;
const created = await save({ ...fresh, title: 'Psalm 4:8' });
const post = calls.find((c) => c.method === 'POST');
check(created.ok && !!post && !('id' in post.body), 'create: a new post lets the database pick the id');
check(!!post && post.body.author_email === 'me@example.org', 'create: the author is recorded');
check(!!post && post.body.slug === 'psalm-4-8-2', 'create: a second post with the same title gets its own address');

await page.evaluate(() => window.LLStore.deletePost(7));
const del = calls.find((c) => c.method === 'DELETE');
check(!!del && del.query.includes('id=eq.7'), 'delete: only that post is removed');

await browser.close();
server.close();
console.log(failures ? `\n${failures} Supabase request check(s) failed` : '\nAll Supabase request checks passed');
process.exit(failures ? 1 : 0);
