#!/usr/bin/env python3
"""Bundle public/ into a single Pages Functions advanced-mode worker (dist/_worker.js).
Used because the Cloudflare connector can deploy _worker.js to Pages but cannot call the
JWT-authenticated asset upload endpoints. Security headers mirror static/_headers."""
import base64, json, pathlib
root = pathlib.Path('public'); out = pathlib.Path('dist'); out.mkdir(exist_ok=True)
CT = {'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.woff2':'font/woff2',
      '.txt':'text/plain; charset=utf-8','.xml':'application/xml; charset=utf-8'}
files = {}
for p in sorted(root.rglob('*')):
    if not p.is_file() or p.name == '_headers': continue
    rel = '/' + str(p.relative_to(root))
    if p.suffix == '.woff2':
        files[rel] = {'t': CT[p.suffix], 'b': base64.b64encode(p.read_bytes()).decode()}
    else:
        files[rel] = {'t': CT[p.suffix], 's': p.read_text()}
worker = """// Little Light legal site (generated by make-worker.py; edit src/ and rebuild instead).
const FILES = %s;
const SECURITY = {
  'Content-Security-Policy': "default-src 'self'; script-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'; upgrade-insecure-requests",
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=(), usb=(), interest-cohort=(), browsing-topics=()',
  'Cross-Origin-Opener-Policy': 'same-origin',
  'Cross-Origin-Resource-Policy': 'same-origin',
};
const BIN = {};
function body(f, path) {
  if (f.s !== undefined) return f.s;
  if (!BIN[path]) { const s = atob(f.b); const a = new Uint8Array(s.length); for (let i = 0; i < s.length; i++) a[i] = s.charCodeAt(i); BIN[path] = a; }
  return BIN[path];
}
function respond(req, url, path, status) {
  const f = FILES[path];
  const h = new Headers(SECURITY);
  h.set('Content-Type', f.t);
  h.set('Cache-Control', path.startsWith('/fonts/') ? 'public, max-age=31536000, immutable' : path.endsWith('.html') ? 'public, max-age=300' : 'public, max-age=3600');
  if (url.hostname.endsWith('.pages.dev')) h.set('X-Robots-Tag', 'noindex');
  return new Response(req.method === 'HEAD' ? null : body(f, path), { status, headers: h });
}
export default {
  async fetch(req) {
    const url = new URL(req.url);
    if (req.method !== 'GET' && req.method !== 'HEAD') return new Response('Method not allowed', { status: 405, headers: { Allow: 'GET, HEAD', ...SECURITY } });
    let p; try { p = decodeURIComponent(url.pathname); } catch (e) { p = '/404.html'; }
    if (p.endsWith('/index.html')) return Response.redirect(url.origin + p.slice(0, -10) + url.search, 308);
    if (p.length > 1 && !p.endsWith('/') && FILES[p + '/index.html']) return Response.redirect(url.origin + p + '/' + url.search, 308);
    const key = p.endsWith('/') ? p + 'index.html' : p;
    if (FILES[key] && key !== '/404.html') return respond(req, url, key, 200);
    return respond(req, url, '/404.html', 404);
  },
};
""" % json.dumps(files, ensure_ascii=False, separators=(',', ':'))
(out / '_worker.js').write_text(worker)
print('dist/_worker.js', len(worker.encode()), 'bytes')
